# Site settings
title: PDG IITR
header-img: img/home-bg.jpg
nav_title: Paper Discussion Group IIT Roorkee
email: your-email@yourdomain.com
copyright_name: Paper Discussion Group IIT Roorkee
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/PDGIITR"
<<<<<<< HEAD
url: "https://balance-breaker.github.io"
=======
url: "http://balance-breaker.github.io"
>>>>>>> c2b5f49c9c1f1dea095d0a7ab3b7ec9d71d38849
twitter_username: SBootstrap
github_username:  Balance-Breaker
facebook_username:  StartBootstrap
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
